---
name: Compile

on: [push]

jobs:
  arduino_ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: arduino/compile-sketches@v1.0.0
      with:
        fqbn: 'arduino:samd:nano33IoT'
        #libraries: |
#         - name: Servo
#         - name: Stepper
#           version: 1.1.3