name: CI

on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "compile"
  compile:
    runs-on: debian-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: arduino/compile-sketches@v1.0.0
        with:
          fqbn: 'arduino:samd:nano33IoT'
#         libraries: |
#           - name: Servo
#           - name: Stepper
#             version: 1.1.3







#---
#name: Compile

#on: [push]

#jobs:
#  arduino_ci:
#    runs-on: ubuntu-latest

#    steps:
#      - uses: actions/checkout@v2
#      - uses: arduino/compile-sketches@v1.0.0
#      with:
#        fqbn: 'arduino:samd:nano33IoT'
        #libraries: |
#         - name: Servo
#         - name: Stepper
#           version: 1.1.3
