- name: Compile Arduino Sketches
  uses: arduino/compile-sketches@v1.0.0
  with:
    fqbn: 'arduino:samd:nano33IoT'
#    libraries: |
#      - name: Servo
#      - name: Stepper
#        version: 1.1.3