name: Test

on: [workflow_dispatch]
#  workflow_dispatch:
#    branches: [unit-tests]
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: lukka/get-cmake@latest
    - name: run-cmake
      uses: lukka/run-cmake@v10.0
      with:
          configurePreset: 'default'
          buildPreset: 'default'
    - name: make
      run: make
#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck
    - name: ctests
      run: ctest
